- name: Installing Packages for Active Directory User Authentication
  hosts: all
  serial: "{{ serial|default(10) }}"

  tasks:

  - command: /usr/bin/zypper --no-gpg-checks --non-interactive -q install -n '{{ item }}'
    with_items:
    - openldap2-client
    - sssd-ad.x86_64
    - samba
