---
#
# Playbook Name: openjdk
#
# Copyright 2013, MapR Technologies
#
# Purpose: Install OpenJDK 1.8 appropriately for Linux release
#
# Run with
#	ansible-playbook <playbook>
# on a local system, or
#	ansible-playbook <playbook> -e "cloud_user=ec2-user" -e "cloud_connection=ssh"
# when accessing remote systems (for example in the Amazon cloud)
#

- name: Installing OpenJDK if required
  hosts: all
  serial: "{{ serial|default(20) }}"



  # Upgrade Suse 1.8 JRE or install 1.8 JDK from scratch
  tasks:
  - zypper: name={{item}} state=latest
    with_items: 
    - java-1_8_0-openjdk-devel
    when: ansible_os_family == 'Suse' 


